.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" Copyright (c) 2011, 2012, 2013 William Hubbs
.\" This is free software; see the GNU General Public Licence version 2
.\" or later for copying conditions.  There is NO warranty.
.TH bugz 1 "20 Jan 2013" "0.10.2"
.nh
.SH NAME
bugz \(em command line interface to bugzilla
.SH SYNOPSIS
.B bugz
[
.B global options
]
.B subcommand
[
.B subcommand options
]
.\" .SH OPTIONS
.\" .TP
.\" .B \-o value, \-\^\-long=value
.\" Describe the option.
.SH DESCRIPTION
Bugz is a cprogram which gives you access to the features of the
bugzilla bug tracking system from the command line.
.PP
This man page is a stub; the bugs program has extensive built in help.
.B bugz -h
will show the help for the global options and
.B bugz [subcommand] -h
will show the help for a specific subcommand.
.SH BUGS
.PP
The home page of this project is http://www.github.com/williamh/pybugz.
Bugs should be reported to the bug tracker there.
.SH SEE ALSO
.PP
For documentation how to configure PyBugz take a look into distributed
.B pybugz.conf
file.  User specific configuration may be defined in
.B
~/.bugzrc
file.
.SH AUTHOR
.PP
The original author is Alastair Tse <alastair@liquidx.net>.
The current maintainer is William Hubbs <w.d.hubbs@gmail.com>. William
also wrote this man page.
