#!/usr/bin/env python3

"""
lbugz: execute bugz from the git repository.

This script is primarily used to test pybugz.
It works by prepending the directory it is located in to sys.path then
importing  pybugz and running the main function from that directory.

This is based on a patch from Mike Frysinger <vapier@gentoo.org>.
"""

import os
import sys
 
sys.path.insert(0, os.path.dirname(__file__))

from bugz.cli import main

if __name__ == "__main__":
	main()
